services:
  app:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      mssql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file:
      - .env
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -Q \"SELECT 1\" || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: masstransit/rabbitmq:4
    container_name: rabbit
    restart: always
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: no
    ports:
      - "16686:16686"
      - "4317:4317"

volumes:
  mssql-data:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local