name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore deps
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Unit tests
        run: |
          for proj in tests/UnitTest/*/*.csproj; do
            dotnet test "$proj" --no-build --configuration Release
          done

  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore deps
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Integration tests
        run: dotnet test tests/IntegrationTest/IntegrationTest.csproj --no-build --configuration Release
